# Generated by Django 2.0.6 on 2018-11-26 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de descuento'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.ProductType', verbose_name='TIpo de producto relacionado'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='release_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de lanzamiento'),
        ),
    ]
