# Generated by Django 2.0.6 on 2018-09-16 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('cost_price', models.FloatField(verbose_name='Precio de compra')),
                ('sale_price', models.FloatField(verbose_name='Precio de venta')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'verbose_name': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=50, verbose_name='Iniciales')),
                ('description', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Producto',
                'verbose_name': 'Tipo de Producto',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.ProductType'),
        ),
    ]
